### ISSUE TITLE
An Issue in conversion of a segmentation model

### ISSUE THREAD

**Issue by rose-jinyang** [azeme1/keras2ncnn#6] opened 2020-12-19 03:04 UTC
Hello
How are you?
I am going to convert a Keras model to a NCNN model.
This model is a person segmentation model and works well.
When converting this model, I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/102679309-d617c700-41e9-11eb-8545-14b326a51f20.png)

I send my model.
https://we.tl/t-fQ2gIoPSDL
Please fix this issue asap.
Thanks

**Comment by azeme1** [comment] 2020-12-19 18:42
This one is related with Conv2DTraspose layer with kernel_size=1
I need time to support this case. Thank for the model. I will try to fix it ASAP.

**Comment by azeme1** [comment] 2020-12-19 19:20
Converted 
====================Test mode from ./run_test.py====================

====================By Layer Comparison ====================
Layer - data :: 1.967195295549118e-08 < 1e-05 True
Layer - Conv1_pad :: 1.9368144421605393e-08 < 1e-05 True
Layer - bn_Conv1 :: 1.9518115834671335e-07 < 1e-05 True
Layer - Conv1_relu_dwc_3 :: 1.8959593717227108e-07 < 1e-05 True
Layer - Conv1_relu :: 1.8955228142658598e-07 < 1e-05 True
Layer - expanded_conv_depthwise_BN :: 5.405697720561875e-07 < 1e-05 True
Layer - expanded_conv_depthwise_relu_dwc_6 :: 4.840361498281709e-07 < 1e-05 True
Layer - expanded_conv_depthwise_relu :: 4.774659601025633e-07 < 1e-05 True
Layer - expanded_conv_project_BN :: 1.2615705600182991e-05 < 1e-05 False
Layer - block_1_expand_BN :: 6.096604920458049e-06 < 1e-05 True
Layer - block_1_expand_relu_dwc_10 :: 3.5072414448222844e-06 < 1e-05 True
Layer - block_1_expand_relu :: 2.6103850814251928e-06 < 1e-05 True
Layer - ncnn_split_1 :: 2.6103850814251928e-06 < 1e-05 True
Layer - ncnn_split_1 :: 2.6103850814251928e-06 < 1e-05 True
Layer - block_1_pad :: 2.5306833322247257e-06 < 1e-05 True
Layer - block_1_depthwise_BN :: 2.1877860945096472e-06 < 1e-05 True
Layer - block_1_depthwise_relu_dwc_14 :: 1.1340217724864488e-06 < 1e-05 True
Layer - block_1_depthwise_relu :: 1.1282301102255587e-06 < 1e-05 True
Layer - block_1_project_BN :: 8.461627658107318e-06 < 1e-05 True
Layer - ncnn_split_2 :: 8.461627658107318e-06 < 1e-05 True
Layer - ncnn_split_2 :: 8.461627658107318e-06 < 1e-05 True
Layer - block_2_expand_BN :: 2.8930280677741393e-06 < 1e-05 True
Layer - block_2_expand_relu_dwc_18 :: 1.583326593390666e-06 < 1e-05 True
Layer - block_2_expand_relu :: 1.4155381222735741e-06 < 1e-05 True
Layer - block_2_depthwise_BN :: 1.8154210010834504e-06 < 1e-05 True
Layer - block_2_depthwise_relu_dwc_21 :: 7.7756226346537e-07 < 1e-05 True
Layer - block_2_depthwise_relu :: 7.720568078184442e-07 < 1e-05 True
Layer - block_2_project_BN :: 1.1687009646266233e-05 < 1e-05 False
Layer - block_2_add :: 1.3620761819765903e-05 < 1e-05 False
Layer - block_3_expand_BN :: 2.4209496132243657e-06 < 1e-05 True
Layer - block_3_expand_relu_dwc_26 :: 1.3797612155030947e-06 < 1e-05 True
Layer - block_3_expand_relu :: 1.3163003131921869e-06 < 1e-05 True
Layer - ncnn_split_3 :: 1.3163003131921869e-06 < 1e-05 True
Layer - ncnn_split_3 :: 1.3163003131921869e-06 < 1e-05 True
Layer - block_3_pad :: 1.2377332723190193e-06 < 1e-05 True
Layer - block_3_depthwise_BN :: 1.3475004152496695e-06 < 1e-05 True
Layer - block_3_depthwise_relu_dwc_30 :: 8.003476068552118e-07 < 1e-05 True
Layer - block_3_depthwise_relu :: 7.932074481686868e-07 < 1e-05 True
Layer - block_3_project_BN :: 9.195880920742638e-06 < 1e-05 True
Layer - ncnn_split_4 :: 9.195880920742638e-06 < 1e-05 True
Layer - ncnn_split_4 :: 9.195880920742638e-06 < 1e-05 True
Layer - block_4_expand_BN :: 1.6447330608571065e-06 < 1e-05 True
Layer - block_4_expand_relu_dwc_34 :: 9.766091579876957e-07 < 1e-05 True
Layer - block_4_expand_relu :: 9.737569826029358e-07 < 1e-05 True
Layer - block_4_depthwise_BN :: 1.4141895690045203e-06 < 1e-05 True
Layer - block_4_depthwise_relu_dwc_37 :: 5.688635269507358e-07 < 1e-05 True
Layer - block_4_depthwise_relu :: 5.688053192898224e-07 < 1e-05 True
Layer - block_4_project_BN :: 5.601700650004204e-06 < 1e-05 True
Layer - block_4_add :: 1.104396960727172e-05 < 1e-05 False
Layer - ncnn_split_5 :: 1.104396960727172e-05 < 1e-05 False
Layer - ncnn_split_5 :: 1.104396960727172e-05 < 1e-05 False
Layer - block_5_expand_BN :: 1.7040716784322285e-06 < 1e-05 True
Layer - block_5_expand_relu_dwc_42 :: 1.3038755923844292e-06 < 1e-05 True
Layer - block_5_expand_relu :: 1.3037397366133519e-06 < 1e-05 True
Layer - block_5_depthwise_BN :: 1.9159158455295255e-06 < 1e-05 True
Layer - block_5_depthwise_relu_dwc_45 :: 5.394866207097948e-07 < 1e-05 True
Layer - block_5_depthwise_relu :: 5.394866207097948e-07 < 1e-05 True
Layer - block_5_project_BN :: 6.0296843003015965e-06 < 1e-05 True
Layer - block_5_add :: 1.2044193681504112e-05 < 1e-05 False
Layer - block_6_expand_BN :: 1.9993558453279547e-06 < 1e-05 True
Layer - block_6_expand_relu_dwc_50 :: 1.02331398466049e-06 < 1e-05 True
Layer - block_6_expand_relu :: 1.0229452982457587e-06 < 1e-05 True
Layer - ncnn_split_6 :: 1.0229452982457587e-06 < 1e-05 True
Layer - ncnn_split_6 :: 1.0229452982457587e-06 < 1e-05 True
Layer - block_6_pad :: 9.061383821062918e-07 < 1e-05 True
Layer - block_6_depthwise_BN :: 8.145545393745124e-07 < 1e-05 True
Layer - block_6_depthwise_relu_dwc_54 :: 5.822914204145491e-07 < 1e-05 True
Layer - block_6_depthwise_relu :: 5.742975872635725e-07 < 1e-05 True
Layer - block_6_project_BN :: 6.029590167599963e-06 < 1e-05 True
Layer - ncnn_split_7 :: 6.029590167599963e-06 < 1e-05 True
Layer - ncnn_split_7 :: 6.029590167599963e-06 < 1e-05 True
Layer - block_7_expand_BN :: 1.0397108098914032e-06 < 1e-05 True
Layer - block_7_expand_relu_dwc_58 :: 6.516620487673208e-07 < 1e-05 True
Layer - block_7_expand_relu :: 6.510411481031042e-07 < 1e-05 True
Layer - block_7_depthwise_BN :: 1.1039311402782914e-06 < 1e-05 True
Layer - block_7_depthwise_relu_dwc_61 :: 3.890937989581289e-07 < 1e-05 True
Layer - block_7_depthwise_relu :: 3.8649386624456383e-07 < 1e-05 True
Layer - block_7_project_BN :: 3.3445312510593794e-06 < 1e-05 True
Layer - block_7_add :: 7.412072591250762e-06 < 1e-05 True
Layer - ncnn_split_8 :: 7.412072591250762e-06 < 1e-05 True
Layer - ncnn_split_8 :: 7.412072591250762e-06 < 1e-05 True
Layer - block_8_expand_BN :: 1.1304641702736262e-06 < 1e-05 True
Layer - block_8_expand_relu_dwc_66 :: 7.190977271420707e-07 < 1e-05 True
Layer - block_8_expand_relu :: 7.18244052677619e-07 < 1e-05 True
Layer - block_8_depthwise_BN :: 1.2627334626813536e-06 < 1e-05 True
Layer - block_8_depthwise_relu_dwc_69 :: 4.3556326545513e-07 < 1e-05 True
Layer - block_8_depthwise_relu :: 4.000565922979149e-07 < 1e-05 True
Layer - block_8_project_BN :: 3.1659387786930893e-06 < 1e-05 True
Layer - block_8_add :: 8.170442015398294e-06 < 1e-05 True
Layer - ncnn_split_9 :: 8.170442015398294e-06 < 1e-05 True
Layer - ncnn_split_9 :: 8.170442015398294e-06 < 1e-05 True
Layer - block_9_expand_BN :: 1.2248818848092924e-06 < 1e-05 True
Layer - block_9_expand_relu_dwc_74 :: 7.083556283760117e-07 < 1e-05 True
Layer - block_9_expand_relu :: 7.023020316410111e-07 < 1e-05 True
Layer - block_9_depthwise_BN :: 1.2683295835813624e-06 < 1e-05 True
Layer - block_9_depthwise_relu_dwc_77 :: 5.007191816730483e-07 < 1e-05 True
Layer - block_9_depthwise_relu :: 4.6284537802421255e-07 < 1e-05 True
Layer - block_9_project_BN :: 3.5477332858135924e-06 < 1e-05 True
Layer - block_9_add :: 8.771283319219947e-06 < 1e-05 True
Layer - block_10_expand_BN :: 1.6151099089256604e-06 < 1e-05 True
Layer - block_10_expand_relu_dwc_82 :: 8.157923616636253e-07 < 1e-05 True
Layer - block_10_expand_relu :: 8.122222538986534e-07 < 1e-05 True
Layer - block_10_depthwise_BN :: 8.089861580629076e-07 < 1e-05 True
Layer - block_10_depthwise_relu_dwc_85 :: 5.323203708940127e-07 < 1e-05 True
Layer - block_10_depthwise_relu :: 5.323203708940127e-07 < 1e-05 True
Layer - block_10_project_BN :: 4.469509349291911e-06 < 1e-05 True
Layer - ncnn_split_10 :: 4.469509349291911e-06 < 1e-05 True
Layer - ncnn_split_10 :: 4.469509349291911e-06 < 1e-05 True
Layer - block_11_expand_BN :: 1.227123675562325e-06 < 1e-05 True
Layer - block_11_expand_relu_dwc_89 :: 6.50364938792336e-07 < 1e-05 True
Layer - block_11_expand_relu :: 6.50364938792336e-07 < 1e-05 True
Layer - block_11_depthwise_BN :: 9.886945235848543e-07 < 1e-05 True
Layer - block_11_depthwise_relu_dwc_92 :: 3.631371896517521e-07 < 1e-05 True
Layer - block_11_depthwise_relu :: 3.586099239782925e-07 < 1e-05 True
Layer - block_11_project_BN :: 3.4224133287352743e-06 < 1e-05 True
Layer - block_11_add :: 5.597503331955522e-06 < 1e-05 True
Layer - ncnn_split_11 :: 5.597503331955522e-06 < 1e-05 True
Layer - ncnn_split_11 :: 5.597503331955522e-06 < 1e-05 True
Layer - block_12_expand_BN :: 1.2821553809772013e-06 < 1e-05 True
Layer - block_12_expand_relu_dwc_97 :: 5.749510592067963e-07 < 1e-05 True
Layer - block_12_expand_relu :: 5.740714641433442e-07 < 1e-05 True
Layer - block_12_depthwise_BN :: 7.788058837832068e-07 < 1e-05 True
Layer - block_12_depthwise_relu_dwc_100 :: 2.5758942001630203e-07 < 1e-05 True
Layer - block_12_depthwise_relu :: 2.5748593657226593e-07 < 1e-05 True
Layer - block_12_project_BN :: 3.66436802323733e-06 < 1e-05 True
Layer - block_12_add :: 6.541242328239605e-06 < 1e-05 True
Layer - block_13_expand_BN :: 1.5131571444726433e-06 < 1e-05 True
Layer - block_13_expand_relu_dwc_105 :: 3.0510238957504043e-07 < 1e-05 True
Layer - block_13_expand_relu :: 3.0510238957504043e-07 < 1e-05 True
Layer - ncnn_split_12 :: 3.0510238957504043e-07 < 1e-05 True
Layer - ncnn_split_12 :: 3.0510238957504043e-07 < 1e-05 True
Layer - block_13_pad :: 2.4106859086714394e-07 < 1e-05 True
Layer - block_13_depthwise_BN :: 3.151531586809142e-07 < 1e-05 True
Layer - block_13_depthwise_relu_dwc_109 :: 2.6817249931809783e-07 < 1e-05 True
Layer - block_13_depthwise_relu :: 2.6817249931809783e-07 < 1e-05 True
Layer - block_13_project_BN :: 2.767143087112345e-06 < 1e-05 True
Layer - ncnn_split_13 :: 2.767143087112345e-06 < 1e-05 True
Layer - ncnn_split_13 :: 2.767143087112345e-06 < 1e-05 True
Layer - block_14_expand_BN :: 7.983365435393353e-07 < 1e-05 True
Layer - block_14_expand_relu_dwc_113 :: 5.392144544202893e-07 < 1e-05 True
Layer - block_14_expand_relu :: 5.392144544202893e-07 < 1e-05 True
Layer - block_14_depthwise_BN :: 7.672863375773886e-07 < 1e-05 True
Layer - block_14_depthwise_relu_dwc_116 :: 2.3196868426111905e-07 < 1e-05 True
Layer - block_14_depthwise_relu :: 2.3196868426111905e-07 < 1e-05 True
Layer - block_14_project_BN :: 1.5626544609403936e-06 < 1e-05 True
Layer - block_14_add :: 3.194465534761548e-06 < 1e-05 True
Layer - ncnn_split_14 :: 3.194465534761548e-06 < 1e-05 True
Layer - ncnn_split_14 :: 3.194465534761548e-06 < 1e-05 True
Layer - block_15_expand_BN :: 8.465784162581258e-07 < 1e-05 True
Layer - block_15_expand_relu_dwc_121 :: 5.310880055731104e-07 < 1e-05 True
Layer - block_15_expand_relu :: 5.310880055731104e-07 < 1e-05 True
Layer - block_15_depthwise_BN :: 6.926800324436044e-07 < 1e-05 True
Layer - block_15_depthwise_relu_dwc_124 :: 1.396607416381812e-07 < 1e-05 True
Layer - block_15_depthwise_relu :: 1.396607416381812e-07 < 1e-05 True
Layer - block_15_project_BN :: 2.7817832233267836e-06 < 1e-05 True
Layer - block_15_add :: 4.082213763467735e-06 < 1e-05 True
Layer - block_16_expand_BN :: 8.869373004927184e-07 < 1e-05 True
Layer - block_16_expand_relu_dwc_129 :: 3.617005859268829e-07 < 1e-05 True
Layer - block_16_expand_relu :: 3.617005859268829e-07 < 1e-05 True
Layer - block_16_depthwise_BN :: 7.660837582079694e-07 < 1e-05 True
Layer - block_16_depthwise_relu_dwc_132 :: 5.425595759334101e-07 < 1e-05 True
Layer - block_16_depthwise_relu :: 5.341776727618708e-07 < 1e-05 True
Layer - block_16_project_BN :: 1.8994511492564925e-06 < 1e-05 True
Layer - conv2d_transpose_1 :: 2.4375676730414852e-05 < 1e-05 False
Layer - batch_normalization_1 :: 3.753242481252528e-07 < 1e-05 True
Layer - activation_1 :: 1.7559548837198236e-07 < 1e-05 True
Layer - concatenate_1 :: 2.222179915634115e-07 < 1e-05 True
Layer - conv2d_transpose_2 :: 9.180153938359581e-06 < 1e-05 True
Layer - batch_normalization_2 :: 4.908004598291882e-07 < 1e-05 True
Layer - activation_2 :: 2.280619071370893e-07 < 1e-05 True
Layer - concatenate_2 :: 4.448483252872393e-07 < 1e-05 True
Layer - conv2d_transpose_3 :: 8.111830538837239e-06 < 1e-05 True
Layer - batch_normalization_3 :: 6.739990681126073e-07 < 1e-05 True
Layer - activation_3 :: 2.726620493831433e-07 < 1e-05 True
Layer - concatenate_3 :: 7.19935599136079e-07 < 1e-05 True
Layer - conv2d_transpose_4 :: 6.485171979875304e-06 < 1e-05 True
Layer - batch_normalization_4 :: 6.369257903315884e-07 < 1e-05 True
Layer - activation_4 :: 2.701866890220117e-07 < 1e-05 True
Layer - concatenate_4 :: 1.2731289871226181e-06 < 1e-05 True
Layer - conv2d_transpose_5 :: 8.13480801298283e-06 < 1e-05 True
Layer - batch_normalization_5 :: 1.232625777447538e-06 < 1e-05 True
Layer - activation_5 :: 4.705362073309516e-07 < 1e-05 True
Layer - conv2d_transpose_6 :: 4.016323600808391e-06 < 1e-05 True
Layer - op :: 8.839469956001267e-08 < 1e-05 True
Layer - flatten_1 :: 8.839469956001267e-08 < 1e-05 True

**Comment by azeme1** [comment] 2020-12-19 19:29
You can reproduce the result with the run_test.py
The path to your should be provided in model_list
```
model_list = [load_model('model_zoo/variouse/issue_00006/deconv_fin_munet.h5')] #issue 6
```

**Comment by azeme1** [comment] 2020-12-19 22:10
In dev branch I have commit the code with the optimization. You can take a look to this model as well

Dropout: Some nodes can de skipped in inference mode
         Transform Error (is less 1e-5) :: 0.0 , True
ReLU: Max Clip is not supported withing NCNN, split by ordinal ReLU and Clip
         Transform Error (is less 1e-5) :: 0.0 , True
Nothing to do with SeparableConv2D transform

Conv2D/DepthwiseConv2D->BatchNormalization: Subsequent linear operations can be easily merged for inference
         Transform Error (is less 1e-5) :: 2.6668203645385802e-08 , True
Nothing to do with BatchNormalization->DepthwiseConv2D transform

Conv2D->ReLU: Inline operations should be merged
         Transform Error (is less 1e-5) :: 2.4985638447105885e-08 , True
Nothing to do with Conv2D->Sigmoid transform

Conv2D->Activation: Inline operations should be merged
         Transform Error (is less 1e-5) :: 2.5776898837648332e-08 , True


====================Test mode from ./run_test.py====================

====================By Layer Comparison ====================
Layer - data :: 1.9640955528643644e-08 < 1e-05 True
Layer - Conv1_pad :: 1.9337624834747658e-08 < 1e-05 True
Layer - bn_Conv1 :: 1.9077029378422594e-07 < 1e-05 True
Layer - Conv1_relu :: 1.906975342080841e-07 < 1e-05 True
Layer - expanded_conv_depthwise_BN :: 4.880391770711867e-07 < 1e-05 True
Layer - expanded_conv_depthwise_relu :: 4.814107796846656e-07 < 1e-05 True
Layer - expanded_conv_project_BN :: 1.2756741853081621e-05 < 1e-05 False
Layer - block_1_expand_BN :: 3.5506393487594323e-06 < 1e-05 True
Layer - block_1_expand_relu :: 2.631462848512456e-06 < 1e-05 True
Layer - ncnn_split_1 :: 2.631462848512456e-06 < 1e-05 True
Layer - ncnn_split_1 :: 2.631462848512456e-06 < 1e-05 True
Layer - block_1_pad :: 2.5511176318104845e-06 < 1e-05 True
Layer - block_1_depthwise_BN :: 1.1432206292738556e-06 < 1e-05 True
Layer - block_1_depthwise_relu :: 1.1375551594028366e-06 < 1e-05 True
Layer - block_1_project_BN :: 8.488475032208953e-06 < 1e-05 True
Layer - ncnn_split_2 :: 8.488475032208953e-06 < 1e-05 True
Layer - ncnn_split_2 :: 8.488475032208953e-06 < 1e-05 True
Layer - block_2_expand_BN :: 1.5852924661885481e-06 < 1e-05 True
Layer - block_2_expand_relu :: 1.4206569858288276e-06 < 1e-05 True
Layer - block_2_depthwise_BN :: 7.864830422477098e-07 < 1e-05 True
Layer - block_2_depthwise_relu :: 7.809242106304737e-07 < 1e-05 True
Layer - block_2_project_BN :: 1.1870894013554789e-05 < 1e-05 False
Layer - block_2_add :: 1.376372529193759e-05 < 1e-05 False
Layer - block_3_expand_BN :: 1.3752602399108582e-06 < 1e-05 True
Layer - block_3_expand_relu :: 1.3142295074430876e-06 < 1e-05 True
Layer - ncnn_split_3 :: 1.3142295074430876e-06 < 1e-05 True
Layer - ncnn_split_3 :: 1.3142295074430876e-06 < 1e-05 True
Layer - block_3_pad :: 1.2357859304756857e-06 < 1e-05 True
Layer - block_3_depthwise_BN :: 8.145955803229299e-07 < 1e-05 True
Layer - block_3_depthwise_relu :: 8.056898082031694e-07 < 1e-05 True
Layer - block_3_project_BN :: 9.259942089556716e-06 < 1e-05 True
Layer - ncnn_split_4 :: 9.259942089556716e-06 < 1e-05 True
Layer - ncnn_split_4 :: 9.259942089556716e-06 < 1e-05 True
Layer - block_4_expand_BN :: 9.82328401732957e-07 < 1e-05 True
Layer - block_4_expand_relu :: 9.78680759544659e-07 < 1e-05 True
Layer - block_4_depthwise_BN :: 5.721735192310007e-07 < 1e-05 True
Layer - block_4_depthwise_relu :: 5.716302098335291e-07 < 1e-05 True
Layer - block_4_project_BN :: 5.741955646954011e-06 < 1e-05 True
Layer - block_4_add :: 1.13220003186143e-05 < 1e-05 False
Layer - ncnn_split_5 :: 1.13220003186143e-05 < 1e-05 False
Layer - ncnn_split_5 :: 1.13220003186143e-05 < 1e-05 False
Layer - block_5_expand_BN :: 1.3243607099866495e-06 < 1e-05 True
Layer - block_5_expand_relu :: 1.3234875950729474e-06 < 1e-05 True
Layer - block_5_depthwise_BN :: 5.428394729278807e-07 < 1e-05 True
Layer - block_5_depthwise_relu :: 5.428394729278807e-07 < 1e-05 True
Layer - block_5_project_BN :: 5.92831429457874e-06 < 1e-05 True
Layer - block_5_add :: 1.2351647455943748e-05 < 1e-05 False
Layer - block_6_expand_BN :: 1.0484733365956345e-06 < 1e-05 True
Layer - block_6_expand_relu :: 1.0469599374118843e-06 < 1e-05 True
Layer - ncnn_split_6 :: 1.0469599374118843e-06 < 1e-05 True
Layer - ncnn_split_6 :: 1.0469599374118843e-06 < 1e-05 True
Layer - block_6_pad :: 9.27410894746572e-07 < 1e-05 True
Layer - block_6_depthwise_BN :: 6.144507551653078e-07 < 1e-05 True
Layer - block_6_depthwise_relu :: 6.059136126168596e-07 < 1e-05 True
Layer - block_6_project_BN :: 6.2837189034326e-06 < 1e-05 True
Layer - ncnn_split_7 :: 6.2837189034326e-06 < 1e-05 True
Layer - ncnn_split_7 :: 6.2837189034326e-06 < 1e-05 True
Layer - block_7_expand_BN :: 6.749049248355732e-07 < 1e-05 True
Layer - block_7_expand_relu :: 6.747497423020832e-07 < 1e-05 True
Layer - block_7_depthwise_BN :: 4.0731603689891926e-07 < 1e-05 True
Layer - block_7_depthwise_relu :: 4.0196093209488026e-07 < 1e-05 True
Layer - block_7_project_BN :: 3.534432380547514e-06 < 1e-05 True
Layer - block_7_add :: 7.690578058827668e-06 < 1e-05 True
Layer - ncnn_split_8 :: 7.690578058827668e-06 < 1e-05 True
Layer - ncnn_split_8 :: 7.690578058827668e-06 < 1e-05 True
Layer - block_8_expand_BN :: 7.390258929262927e-07 < 1e-05 True
Layer - block_8_expand_relu :: 7.389094776044658e-07 < 1e-05 True
Layer - block_8_depthwise_BN :: 4.632105401469744e-07 < 1e-05 True
Layer - block_8_depthwise_relu :: 4.1765335367927037e-07 < 1e-05 True
Layer - block_8_project_BN :: 3.5683483474713285e-06 < 1e-05 True
Layer - block_8_add :: 8.312221325468272e-06 < 1e-05 True
Layer - ncnn_split_9 :: 8.312221325468272e-06 < 1e-05 True
Layer - ncnn_split_9 :: 8.312221325468272e-06 < 1e-05 True
Layer - block_9_expand_BN :: 7.263809607138683e-07 < 1e-05 True
Layer - block_9_expand_relu :: 7.173782137215312e-07 < 1e-05 True
Layer - block_9_depthwise_BN :: 5.395280027187255e-07 < 1e-05 True
Layer - block_9_depthwise_relu :: 4.968423468199035e-07 < 1e-05 True
Layer - block_9_project_BN :: 3.6812432426813757e-06 < 1e-05 True
Layer - block_9_add :: 8.852930477587506e-06 < 1e-05 True
Layer - block_10_expand_BN :: 8.194435849873116e-07 < 1e-05 True
Layer - block_10_expand_relu :: 8.1505862681297e-07 < 1e-05 True
Layer - block_10_depthwise_BN :: 5.466650350172131e-07 < 1e-05 True
Layer - block_10_depthwise_relu :: 5.466650350172131e-07 < 1e-05 True
Layer - block_10_project_BN :: 4.602733952197013e-06 < 1e-05 True
Layer - ncnn_split_10 :: 4.602733952197013e-06 < 1e-05 True
Layer - ncnn_split_10 :: 4.602733952197013e-06 < 1e-05 True
Layer - block_11_expand_BN :: 6.70750523568131e-07 < 1e-05 True
Layer - block_11_expand_relu :: 6.70750523568131e-07 < 1e-05 True
Layer - block_11_depthwise_BN :: 3.787226319218462e-07 < 1e-05 True
Layer - block_11_depthwise_relu :: 3.713238072577951e-07 < 1e-05 True
Layer - block_11_project_BN :: 3.5990096876048483e-06 < 1e-05 True
Layer - block_11_add :: 5.8217119658365846e-06 < 1e-05 True
Layer - ncnn_split_11 :: 5.8217119658365846e-06 < 1e-05 True
Layer - ncnn_split_11 :: 5.8217119658365846e-06 < 1e-05 True
Layer - block_12_expand_BN :: 6.04288516115048e-07 < 1e-05 True
Layer - block_12_expand_relu :: 6.036159447830869e-07 < 1e-05 True
Layer - block_12_depthwise_BN :: 2.8084954806217866e-07 < 1e-05 True
Layer - block_12_depthwise_relu :: 2.8084954806217866e-07 < 1e-05 True
Layer - block_12_project_BN :: 4.021691438538255e-06 < 1e-05 True
Layer - block_12_add :: 6.8783069764322136e-06 < 1e-05 True
Layer - block_13_expand_BN :: 3.161616177749238e-07 < 1e-05 True
Layer - block_13_expand_relu :: 3.161616177749238e-07 < 1e-05 True
Layer - ncnn_split_12 :: 3.161616177749238e-07 < 1e-05 True
Layer - ncnn_split_12 :: 3.161616177749238e-07 < 1e-05 True
Layer - block_13_pad :: 2.4980673174468393e-07 < 1e-05 True
Layer - block_13_depthwise_BN :: 2.6269356112607056e-07 < 1e-05 True
Layer - block_13_depthwise_relu :: 2.6269356112607056e-07 < 1e-05 True
Layer - block_13_project_BN :: 2.7393157324695494e-06 < 1e-05 True
Layer - ncnn_split_13 :: 2.7393157324695494e-06 < 1e-05 True
Layer - ncnn_split_13 :: 2.7393157324695494e-06 < 1e-05 True
Layer - block_14_expand_BN :: 5.209433879826975e-07 < 1e-05 True
Layer - block_14_expand_relu :: 5.209433879826975e-07 < 1e-05 True
Layer - block_14_depthwise_BN :: 2.3019480011043925e-07 < 1e-05 True
Layer - block_14_depthwise_relu :: 2.3019480011043925e-07 < 1e-05 True
Layer - block_14_project_BN :: 1.618426949789864e-06 < 1e-05 True
Layer - block_14_add :: 3.2602633837086614e-06 < 1e-05 True
Layer - ncnn_split_14 :: 3.2602633837086614e-06 < 1e-05 True
Layer - ncnn_split_14 :: 3.2602633837086614e-06 < 1e-05 True
Layer - block_15_expand_BN :: 5.140784082868777e-07 < 1e-05 True
Layer - block_15_expand_relu :: 5.140784082868777e-07 < 1e-05 True
Layer - block_15_depthwise_BN :: 1.3942614884854265e-07 < 1e-05 True
Layer - block_15_depthwise_relu :: 1.3942614884854265e-07 < 1e-05 True
Layer - block_15_project_BN :: 2.6617644834914245e-06 < 1e-05 True
Layer - block_15_add :: 4.280160737835104e-06 < 1e-05 True
Layer - block_16_expand_BN :: 4.1044023646463756e-07 < 1e-05 True
Layer - block_16_expand_relu :: 4.1044023646463756e-07 < 1e-05 True
Layer - block_16_depthwise_BN :: 6.12174346770189e-07 < 1e-05 True
Layer - block_16_depthwise_relu :: 5.994462526359712e-07 < 1e-05 True
Layer - block_16_project_BN :: 2.2885913040227024e-06 < 1e-05 True
Layer - conv2d_transpose_1 :: 2.124357791899456e-07 < 1e-05 True
Layer - concatenate_1 :: 2.49777087901748e-07 < 1e-05 True
Layer - conv2d_transpose_2 :: 2.5654631485849677e-07 < 1e-05 True
Layer - concatenate_2 :: 4.7211366904775787e-07 < 1e-05 True
Layer - conv2d_transpose_3 :: 2.743203992849885e-07 < 1e-05 True
Layer - concatenate_3 :: 7.19995625786396e-07 < 1e-05 True
Layer - conv2d_transpose_4 :: 2.809465229347552e-07 < 1e-05 True
Layer - concatenate_4 :: 1.2883108411188005e-06 < 1e-05 True
Layer - conv2d_transpose_5 :: 4.799697990165441e-07 < 1e-05 True
Layer - conv2d_transpose_6 :: 9.911764209391549e-08 < 1e-05 True
Layer - flatten_1 :: 9.911764209391549e-08 < 1e-05 True

**Comment by rose-jinyang** [comment] 2020-12-21 16:24
Hi
Are u sure that this issue was fixed and the model is converted exactly?
That's why the result from NCNN is different from the original.

**Comment by azeme1** [comment] 2020-12-21 16:43
According to my tests - yes!21.12.2020, 19:25, "rose-jinyang" <notifications@github.com>:
Hi
Are u sure that this issue was fixed and the model is converted exactly?
That's why the result from NCNN is different from the original.

**Comment by azeme1** [comment] 2020-12-28 08:05
The problem is found. I close the issue because of no activity.

**Closed as completed by azeme1** 2020-12-28 08:05 UTC
